name: Build Flarial from Source

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.31.x'
    - name: Patch libhat
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir build
        cd build
        cmake ..
        <#
        $content = @"
        #include <libhat/Process.hpp>
        #include <string>
        
        namespace hat::process {
        
            module_t module_at(uintptr_t address) {
                return module_t{address};
            }
        
            module_t module_at(std::byte* address) {
                return module_at(reinterpret_cast<uintptr_t>(address));
            }
        }
        "@
        # Get-ChildItem -Path "D:\" -Filter "Process.cpp" -Recurse
        Set-Content  D:\a\flarial-dll\flarial-dll\build\_deps\libhat-src\src\Process.cpp -Value $content -Force #>
    - name: Build Flarial
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd build
        cmake --build .
    - name: Confirm Test
      run: dcho "This message should show up if the thing ran sucessfully"
